spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/codi?serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      # for development phase only
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        # format_sql: true
        use_sql_comments: true

server:
  port: ${PORT:8080}

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
    root: INFO
