spring:
  datasource:
    url: jdbc:h2:mem:codi
    driverClassName: org.h2.Driver
    username: yunhong
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        # format_sql: true
        use_sql_comments: true
  h2:
    console:
      enabled: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
    root: INFO
